language: node_js
stages:
  - test
  - name: deploy
    if: branch = temporary-track
os:
  - linux
node_js:
  - "8"
#script:
#  - npm install
branches:
  except:
  # because this is a github personal page, only master 
  # is published. Thus, Travis musn't build from that!
  - master

jobs:
  include:
    - stage: test
      script:
        - npm run lint
    - stage: deploy
      script:
        - npm run deploy